### ISSUE TITLE
Error: “WebCryptoAPI is not available”

### ISSUE THREAD

**Issue by DDimovska** [sigp/ecies-parity#2]
Hello,

I tried to run the example for ECIES with node in console, but I got this error: “WebCryptoAPI is not available” …

**Comment by bitsanity** [comment]
I am getting same problem

`at Object.exports.decrypt (/home/myacct/node_modules/ecies-parity/browser.js:163:3)`

It is picking up browser.js even though I am running in node.js environment v17.3.0 in Ubuntu. I trace it to the following line in index.js file:

`var ecdh = require("./build/Release/ecdh");`

**Root cause**: the ecdh is missing from the Release.

I try to build it. I'm supposed to use node-gyp to compile it but node-gyp won't install on my system, I guess because I am using the latest distribution of node.js and not the stable.

`Some packages could not be installed. This may mean that you have requested an impossible situation or if you are using the unstable distribution that some required packages have not yet been created or been moved out of Incoming.`
